name: time_picker_wheel
description: Time Picker inspired by Oppo Clock app set alram time screen with full customization
version: 0.1.1
homepage: https://github.com/burhankhanzada/time_picker_wheel

topics:
  - time
  - picker
  - wheek

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  provider: ^6.0.5
  spaces2: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
